// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type AnalyticsEvent struct {
	ID          uuid.UUID `db:"id" json:"id"`
	CardID      uuid.UUID `db:"card_id" json:"card_id"`
	PunchCardID uuid.UUID `db:"punch_card_id" json:"punch_card_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	BusinessID  uuid.UUID `db:"business_id" json:"business_id"`
	Type        string    `db:"type" json:"type"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

type BusinessLocation struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	BusinessID uuid.UUID  `db:"business_id" json:"business_id"`
	Name       string     `db:"name" json:"name"`
	Country    string     `db:"country" json:"country"`
	City       string     `db:"city" json:"city"`
	Address    string     `db:"address" json:"address"`
	Phone      string     `db:"phone" json:"phone"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type BusinessPunchCard struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	BusinessID     uuid.UUID  `db:"business_id" json:"business_id"`
	Name           string     `db:"name" json:"name"`
	Description    string     `db:"description" json:"description"`
	Details        *string    `db:"details" json:"details"`
	StampCount     int32      `db:"stamp_count" json:"stamp_count"`
	JoinStampCount int32      `db:"join_stamp_count" json:"join_stamp_count"`
	IsPrivate      bool       `db:"is_private" json:"is_private"`
	CardImageID    uuid.UUID  `db:"card_image_id" json:"card_image_id"`
	StampImageID   uuid.UUID  `db:"stamp_image_id" json:"stamp_image_id"`
	Status         string     `db:"status" json:"status"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt      *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt      *time.Time `db:"deleted_at" json:"deleted_at"`
}

type BusinessReward struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	Name          string     `db:"name" json:"name"`
	ExpiresAfter  int32      `db:"expires_after" json:"expires_after"`
	RewardImageID uuid.UUID  `db:"reward_image_id" json:"reward_image_id"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt     *time.Time `db:"deleted_at" json:"deleted_at"`
}

type BusinessStampLink struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	BusinessID uuid.UUID  `db:"business_id" json:"business_id"`
	Type       string     `db:"type" json:"type"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type CoreBusiness struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Website   string     `db:"website" json:"website"`
	Socials   []byte     `db:"socials" json:"socials"`
	Email     string     `db:"email" json:"email"`
	Features  []byte     `db:"features" json:"features"`
	Status    string     `db:"status" json:"status"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
}

type CoreBusinessUser struct {
	UserID     uuid.UUID  `db:"user_id" json:"user_id"`
	BusinessID uuid.UUID  `db:"business_id" json:"business_id"`
	Owner      bool       `db:"owner" json:"owner"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type CoreSession struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	UserID     uuid.UUID  `db:"user_id" json:"user_id"`
	Ip         *string    `db:"ip" json:"ip"`
	Device     *string    `db:"device" json:"device"`
	UserAgent  *string    `db:"user_agent" json:"user_agent"`
	Os         *string    `db:"os" json:"os"`
	Location   *string    `db:"location" json:"location"`
	SignInAt   *time.Time `db:"sign_in_at" json:"sign_in_at"`
	ExpiresAt  *time.Time `db:"expires_at" json:"expires_at"`
	RememberMe bool       `db:"remember_me" json:"remember_me"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
}

type CoreUser struct {
	ID                    uuid.UUID  `db:"id" json:"id"`
	FirstName             string     `db:"first_name" json:"first_name"`
	LastName              string     `db:"last_name" json:"last_name"`
	PasswordDigest        string     `db:"password_digest" json:"password_digest"`
	Language              string     `db:"language" json:"language"`
	Timezone              string     `db:"timezone" json:"timezone"`
	Email                 string     `db:"email" json:"email"`
	EmailVerifiedAt       *time.Time `db:"email_verified_at" json:"email_verified_at"`
	PhoneVerificationCode *string    `db:"phone_verification_code" json:"phone_verification_code"`
	CreatedAt             time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt             *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt             *time.Time `db:"deleted_at" json:"deleted_at"`
}

type CustomerCard struct {
	ID                   uuid.UUID  `db:"id" json:"id"`
	UserID               uuid.UUID  `db:"user_id" json:"user_id"`
	PunchCardID          uuid.UUID  `db:"punch_card_id" json:"punch_card_id"`
	StampCount           int32      `db:"stamp_count" json:"stamp_count"`
	LastStampAt          *time.Time `db:"last_stamp_at" json:"last_stamp_at"`
	LastRewardRedeemedAt *time.Time `db:"last_reward_redeemed_at" json:"last_reward_redeemed_at"`
	CreatedAt            time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt            *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt            *time.Time `db:"deleted_at" json:"deleted_at"`
}

type CustomerSession struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	UserID     uuid.UUID  `db:"user_id" json:"user_id"`
	Ip         *string    `db:"ip" json:"ip"`
	Device     *string    `db:"device" json:"device"`
	UserAgent  *string    `db:"user_agent" json:"user_agent"`
	Os         *string    `db:"os" json:"os"`
	Location   *string    `db:"location" json:"location"`
	SignInAt   *time.Time `db:"sign_in_at" json:"sign_in_at"`
	ExpiresAt  *time.Time `db:"expires_at" json:"expires_at"`
	RememberMe bool       `db:"remember_me" json:"remember_me"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
}

type CustomerUser struct {
	ID                    uuid.UUID  `db:"id" json:"id"`
	FirstName             string     `db:"first_name" json:"first_name"`
	LastName              string     `db:"last_name" json:"last_name"`
	PasswordDigest        string     `db:"password_digest" json:"password_digest"`
	Language              string     `db:"language" json:"language"`
	Timezone              string     `db:"timezone" json:"timezone"`
	Phone                 string     `db:"phone" json:"phone"`
	PhoneVerifiedAt       *time.Time `db:"phone_verified_at" json:"phone_verified_at"`
	PhoneVerificationCode *string    `db:"phone_verification_code" json:"phone_verification_code"`
	CreatedAt             time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt             *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt             *time.Time `db:"deleted_at" json:"deleted_at"`
}

type MailTemplate struct {
	TemplateID string     `db:"template_id" json:"template_id"`
	Title      string     `db:"title" json:"title"`
	Language   string     `db:"language" json:"language"`
	Body       string     `db:"body" json:"body"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}

type MediaImage struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	BusinessID uuid.UUID  `db:"business_id" json:"business_id"`
	FileSize   int64      `db:"file_size" json:"file_size"`
	FileType   string     `db:"file_type" json:"file_type"`
	Bucket     string     `db:"bucket" json:"bucket"`
	Path       string     `db:"path" json:"path"`
	Type       string     `db:"type" json:"type"`
	Status     string     `db:"status" json:"status"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt  *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt  *time.Time `db:"deleted_at" json:"deleted_at"`
}
